import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { 
  Zap, 
  Users, 
  Trophy, 
  ArrowRight,
  Star,
  Play,
  ChevronDown
} from 'lucide-react';
import QuollMascot from '../components/QuollMascot';

const LandingPage: React.FC = () => {
  const features = [
    {
      icon: Zap,
      title: 'AI-Powered Quizzes',
      description: 'Dynamic questions generated by AI for endless learning challenges'
    },
    {
      icon: QuollMascot,
      title: 'Fantasy Adventure',
      description: 'Embark on epic quests through mystical learning realms'
    },
    {
      icon: Users,
      title: 'Community Learning',
      description: 'Connect with fellow adventurers in the Quoll\'s Den'
    },
    {
      icon: Trophy,
      title: 'Leveling System',
      description: 'Gain EXP, unlock achievements, and climb the leaderboards'
    }
  ];

  const testimonials = [
    {
      name: 'Alex Chen',
      role: 'Software Developer',
      content: 'QuollQuest transformed how I learn new technologies. The gamification keeps me motivated!',
      avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    },
    {
      name: 'Sarah Johnson',
      role: 'Data Scientist',
      content: 'The AI-generated questions are incredibly relevant and challenging. Love the fantasy theme!',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    },
    {
      name: 'Marcus Rodriguez',
      role: 'Student',
      content: 'Finally, learning that doesn\'t feel like work. The quest system is addictive in the best way!',
      avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    }
  ];

  return (
    <div className="min-h-screen bg-fantasy-bg text-white overflow-hidden relative">
      {/* Bolt Badge - Fixed Position */}
      <motion.a
        href="https://bolt.new"
        target="_blank"
        rel="noopener noreferrer"
        initial={{ opacity: 0, scale: 0.8, y: -20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 1 }}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className="fixed top-4 right-4 z-50 group"
      >
        <div className="relative">
          {/* Badge Image */}
          <img
            src="/badge bolt.png"
            alt="Powered by Bolt"
            className="w-16 h-16 md:w-20 md:h-20 transition-all duration-300 group-hover:drop-shadow-lg"
          />
          
          {/* Glow Effect on Hover */}
          <div className="absolute inset-0 bg-primary-500/20 rounded-full blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 -z-10"></div>
          
          {/* Tooltip */}
          <div className="absolute bottom-full right-0 mb-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none">
            <div className="bg-dark-card/90 backdrop-blur-sm text-white text-xs px-3 py-2 rounded-lg border border-primary-800/30 whitespace-nowrap">
              Built with Bolt.new
              <div className="absolute top-full right-4 w-0 h-0 border-l-4 border-r-4 border-t-4 border-transparent border-t-dark-card/90"></div>
            </div>
          </div>
        </div>
      </motion.a>

      {/* Animated Background Elements */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        {[...Array(20)].map((_, i) => (
          <motion.div
            key={i}
            className="absolute w-1 h-1 bg-primary-400 rounded-full"
            animate={{
              x: [0, Math.random() * window.innerWidth],
              y: [0, Math.random() * window.innerHeight],
              opacity: [0, 1, 0],
            }}
            transition={{
              duration: Math.random() * 10 + 10,
              repeat: Infinity,
              delay: Math.random() * 5,
            }}
          />
        ))}
      </div>

      {/* Hero Section */}
      <section className="relative pt-20 pb-32 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="mb-8"
          >
            <div className="flex justify-center mb-6">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                className="w-20 h-20 bg-gradient-to-r from-primary-500 to-fantasy-purple rounded-full flex items-center justify-center shadow-2xl shadow-primary-500/25 p-2"
              >
                <QuollMascot animate={false} size="lg" className="w-full h-full text-white" />
              </motion.div>
            </div>
            <h1 className="text-6xl md:text-8xl font-bold mb-6 bg-gradient-to-r from-primary-400 via-fantasy-purple to-primary-600 bg-clip-text text-transparent">
              QuollQuest
            </h1>
            <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-3xl mx-auto leading-relaxed">
              Your Agile Learning Adventure Awaits
            </p>
            <p className="text-lg text-gray-400 mb-12 max-w-2xl mx-auto">
              Embark on epic learning quests with AI-powered challenges, fantasy adventures, and gamified progression. Transform your learning journey into an addictive adventure!
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="flex flex-col sm:flex-row gap-4 justify-center items-center"
          >
            <Link to="/login">
              <motion.button
                whileHover={{ scale: 1.05, boxShadow: "0 20px 40px rgba(59, 130, 246, 0.3)" }}
                whileTap={{ scale: 0.95 }}
                className="bg-gradient-to-r from-primary-600 to-primary-700 hover:from-primary-700 hover:to-primary-800 px-8 py-4 rounded-xl font-semibold text-lg flex items-center space-x-2 shadow-xl transition-all duration-300"
              >
                <Play className="w-5 h-5" />
                <span>Start Your Adventure</span>
                <ArrowRight className="w-5 h-5" />
              </motion.button>
            </Link>
            <a href='https://youtu.be/AJ82XbKSZL4' target="_blank" rel="noopener noreferrer">
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="border-2 border-primary-500 hover:bg-primary-500/10 px-8 py-4 rounded-xl font-semibold text-lg flex items-center space-x-2 transition-all duration-300"
              >
                <span>Watch Demo</span>
                </motion.button>
              </a>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.8 }}
            className="mt-16 flex justify-center"
          >
            <motion.div
              animate={{ y: [0, 10, 0] }}
              transition={{ duration: 2, repeat: Infinity }}
            >
              <ChevronDown className="w-8 h-8 text-primary-400" />
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 relative">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">
              Epic Features Await
            </h2>
            <p className="text-xl text-gray-400 max-w-2xl mx-auto">
              Discover the magical elements that make QuollQuest the ultimate learning adventure
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  whileHover={{ y: -10, scale: 1.02 }}
                  className="bg-dark-card/50 backdrop-blur-sm p-8 rounded-2xl border border-primary-800/30 hover:border-primary-600/50 transition-all duration-300 group"
                >
                  <div className="mb-6">
                    <div className="w-16 h-16 bg-gradient-to-r from-primary-500 to-fantasy-purple rounded-xl flex items-center justify-center group-hover:animate-pulse-glow transition-all duration-300 p-2">
                      {Icon === QuollMascot ? (
                        <QuollMascot animate={true} size="lg" className="w-full h-full text-white" />
                      ) : (
                        <Icon className="w-8 h-8 text-white" />
                      )}
                    </div>
                  </div>
                  <h3 className="text-xl font-bold mb-4 text-white group-hover:text-primary-300 transition-colors">
                    {feature.title}
                  </h3>
                  <p className="text-gray-400 leading-relaxed">
                    {feature.description}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-dark-surface/30">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-fantasy-gold to-fantasy-emerald bg-clip-text text-transparent">
              Adventurer Stories
            </h2>
            <p className="text-xl text-gray-400 max-w-2xl mx-auto">
              Hear from fellow questers who transformed their learning journey
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={testimonial.name}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                whileHover={{ y: -5 }}
                className="bg-dark-card/60 backdrop-blur-sm p-8 rounded-2xl border border-primary-800/30 hover:border-fantasy-gold/50 transition-all duration-300"
              >
                <div className="flex items-center mb-6">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full mr-4 border-2 border-primary-500"
                  />
                  <div>
                    <h4 className="font-bold text-white">{testimonial.name}</h4>
                    <p className="text-gray-400 text-sm">{testimonial.role}</p>
                  </div>
                </div>
                <div className="flex mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 text-fantasy-gold fill-current" />
                  ))}
                </div>
                <p className="text-gray-300 italic leading-relaxed">
                  "{testimonial.content}"
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h2 className="text-4xl md:text-6xl font-bold mb-8 bg-gradient-to-r from-primary-400 to-fantasy-purple bg-clip-text text-transparent">
              Ready to Begin?
            </h2>
            <p className="text-xl text-gray-300 mb-12 max-w-2xl mx-auto">
              Join thousands of adventurers already leveling up their skills through epic learning quests
            </p>
            <Link to="/signup">
              <motion.button
                whileHover={{ 
                  scale: 1.05, 
                  boxShadow: "0 25px 50px rgba(59, 130, 246, 0.4)",
                }}
                whileTap={{ scale: 0.95 }}
                className="bg-gradient-to-r from-primary-600 via-fantasy-purple to-primary-700 hover:from-primary-700 hover:via-fantasy-purple hover:to-primary-800 px-12 py-6 rounded-2xl font-bold text-xl flex items-center space-x-3 mx-auto shadow-2xl transition-all duration-300 animate-glow"
              >
                <QuollMascot animate={true} size="md" className="text-white" />
                <span>Begin Your Quest</span>
                <ArrowRight className="w-6 h-6" />
              </motion.button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 sm:px-6 lg:px-8 border-t border-primary-800/30 bg-dark-surface/50">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex justify-center items-center space-x-2 mb-4">
            <QuollMascot animate={true} size="md" className="text-primary-500" />
            <span className="text-xl font-bold bg-gradient-to-r from-primary-400 to-fantasy-purple bg-clip-text text-transparent">
              QuollQuest
            </span>
          </div>
          <p className="text-gray-400">
            © 2025 QuollQuest. Embark on your learning adventure today.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;